(let ((projectdir "~/.local/src/steamacs/"))
  (load (concat projectdir "steam-mod-launch-options.el"))
  (load (concat projectdir "steam-getinfo.el"))
  (load (concat projectdir "steam-recentf.el"))
  (load (concat projectdir "steam-game-menu.el")))
