#+title: Welcome to Steamacs!
#+author: t3mpt0n
#+date: 2023-05-05
#+language: en
Para leer este archivo en español, haz clic [[./LEEME.org][aquí.]]

* Intro
*GabeNU-Steamacs* is a WIP Emacs Steam Launcher. Here are the features available to you at the moment:
- =M-x counsel-steam-game-menu= :: Returns a menu listing your Steam Library.
- =M-x counsel-steam-recentf= :: Returns a menu listing your recently played Steam games.
- =M-x counsel-steam-game-mod-launchopt= :: Like game-menu but edits your launch options.

* How to install
To install *GabeNU-Steamacs*, add this to your =init.el=:
#+BEGIN_SRC emacs-lisp
(add-to-list 'load-path "STEAMACS_INSTALL_DIRECTORY") ;; Replace "STEAMACS_INSTALL_DIRECTORY" with the directory of your Steamacs install
(require 'counsel-steam-game-menu)
(require 'counsel-steam-recentf)
(require 'counsel-steam-game-mod-launchopt)
(setq steam_api_key "YOUR_STEAM_API_KEY_HERE") ;; Register or get your api key here: https://steamcommunity.com/dev/apikey
(setq steam_account_id "AccountID") ;; Go to `https://steamdb.info/calculator` and copy the numbers from 'AccountID'
(setq steam_id "SteamID") ;; Go to `https://steamdb.info/calculator` and copy the numbers from 'SteamID'
(setq steamdir "steamacs") ;; OPTIONAL ;; name of steamacs cache directory on .emacs.d
(setq steamlauncher_sh "<EMACS_DIR>/<STEAMDIR>/steamlauncher.sh") ;; OPTIONAL ;; path for steamlauncher.sh that Steamacs uses to launch steam games.
#+END_SRC

To have *GabeNU-Steamacs* working properly, make sure that the =vdf= module for python is installed:
#+BEGIN_SRC sh
pip install vdf
#+END_SRC


If you have NixOS you can do the following:
#+BEGIN_SRC nix
environment.systemPackages = with pkgs; [
  (python311.withPackages (p: with p; [
    pip
    vdf
  ]))
]
#+END_SRC

or if you have home-manager you can do this:
#+BEGIN_SRC nix
home.packages = with pkgs; [
  (python311.withPackages (p: with p; [
    pip
    vdf
  ]))
]
#+END_SRC

* Special Thanks
- [[https://github.com/Phundrak][Phundrak]] :: For suggesting I don't hardcode =~/.emacs.d=.

* WIP/TODO
- Proton Menu Implentation
- Steam Store
